use std::sync::Arc;

use bevy::prelude::*;

use fedry_bevy_plugin::bevy_system_service::BevySystemService;
use fedry_bevy_plugin::prelude::*;
use fedry_runtime::prelude::*;

use crate::game::SpawnPaletteMaterial;

/// Register game-specific functions.
///
/// :see [fedry_bevy_plugin::bevy_call_funcs] for the common ones.
///
pub(crate) fn register_funcs(mut commands: Commands, runtime: Res<ScriptRuntime>) {
    let rt = &runtime.rt;
    let bevy_system_service = rt.get_service::<BevySystemService>().expect("expected BevySystemService");

    bevy_system_service.add_runtime_system(
        rt.pool.for_str("set_palette_material"),
        commands.register_system(set_palette_material));

}

/// Policy for the object(s) generated by the `spawn_cube` call.
#[derive(Debug, Default, Clone, Copy, PartialEq)]
#[derive(Reflect)]
#[type_path = "game"]
pub(crate) enum Lifetime {
    /// Create as a temporary object, which will be despawned
    /// after a given amount of game time.
    Temporary{ secs: f32 },
    /// Try to keep the object (default).
    /// This is typically bounded by the current level's end.
    #[default]
    Forever,
}

/// Set the material to use our palette-mapped extension.
pub(crate) fn set_palette_material(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    mut commands: Commands,
) -> ExecResult {
    if args.len() != 0 {
        return Err(RuntimeError::TooManyArguments(
            Arc::new(BlockId(None, rt.pool.ensure_str_ref("set_palette_material"))),
            args.len() as ArgIndex, 0));
    }

    commands.entity(entity).insert(SpawnPaletteMaterial);

    Ok(default())
}
