use bevy::prelude::*;

/// Register game-specific functions.
///
/// :see [fedry_bevy_plugin::bevy_call_funcs] for the common ones.
///
pub(crate) fn register_funcs(/* mut commands: Commands, runtime: Res<ScriptRuntime> */) {
    /*
    use std::sync::Arc;
    use fedry_bevy_plugin::bevy_system_service::BevySystemService;
    use fedry_bevy_plugin::prelude::*;
    let rt = &runtime.rt;
    let bevy_system_service = rt.get_service::<BevySystemService>().expect("expected BevySystemService"); */
}

/// Policy for the object(s) generated by the `spawn_cube` call.
#[derive(Debug, Default, Clone, Copy, PartialEq)]
#[derive(Reflect)]
#[type_path = "game"]
pub(crate) enum Lifetime {
    /// Create as a temporary object, which will be despawned
    /// after a given amount of game time.
    Temporary{ secs: f32 },
    /// Try to keep the object (default).
    /// This is typically bounded by the current level's end.
    #[default]
    Forever,
}
