use std::sync::Arc;

use avian3d::math::AdjustPrecision as _;
use bevy::ecs::world::CommandQueue;
use bevy::gltf::GltfMesh;
use eds_bevy_common::*;

use avian3d::prelude::*;
use bevy::prelude::*;

use fedry_bevy_plugin::bevy_system_service::BevySystemService;
use fedry_bevy_plugin::prelude::*;
use fedry_runtime::prelude::*;

use crate::assets::ModelAssets;
use crate::game::Cube;
use crate::game::OurMidiSynth;
use crate::game::SpawnPaletteMaterial;

/// Register game-specific functions.
///
/// :see [fedry_bevy_plugin::bevy_call_funcs] for the common ones.
///
pub(crate) fn register_funcs(mut commands: Commands, runtime: Res<ScriptRuntime>) {
    let rt = &runtime.rt;
    let bevy_system_service = rt.get_service::<BevySystemService>().expect("expected BevySystemService");

    bevy_system_service.add_runtime_system(
        rt.pool.for_str("spawn_cube"),
        commands.register_system(spawn_cube));

    bevy_system_service.add_runtime_system(
        rt.pool.for_str("set_palette_material"),
        commands.register_system(set_palette_material));

}

/// Attributes for a `spawn_cube` call.
#[derive(Reflect, Debug, Clone)]
pub(crate) struct SpawnInfo {
    /// Offset to spawn relative to the caller's position.
    pub offset: Vec3,
    /// Size of object, in m.
    pub size: Vec3,
    /// Direction the object should be oriented. Default is Vec3::ZERO.
    pub angle: Vec3,
    pub color: Color,
    pub mass: f32,
    pub is_static: bool,
    /// The rules for the item.
    pub life_policy: SpawnedLifetimePolicy,
    pub has_synth: bool,
}

/// Policy for the object(s) generated by the `spawn_cube` call.
#[derive(Debug, Default, Clone, Copy, PartialEq)]
#[derive(Reflect)]
#[type_path = "game"]
pub enum SpawnedLifetimePolicy {
    /// Create as a temporary object, which will be despawned
    /// after a given amount of game time.
    Temporary{ secs: f32 },
    /// (Try to) keep the object.
    /// This is typically bounded by the current level's end.
    #[default]
    Keep,
}

impl Default for SpawnInfo {
    fn default() -> Self {
        Self {
            offset: Vec3::ZERO,
            size: Vec3::splat(1.0),
            color: Color::WHITE,
            angle: Vec3::ZERO,
            mass: 1.0,
            is_static: false,
            life_policy: SpawnedLifetimePolicy::Keep,
            has_synth: false,
        }
    }
}

pub(crate) fn spawn_cube(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>, world: &mut World) -> ExecResult {
    if args.is_empty() {
        return Err(RuntimeError::MissingArgument(0));
    }

    let xfrm = {
        let mut query = world.query::<&Transform>();
        query.get(world, entity).map(|x| *x).unwrap_or_default()
    };
    let world_entity = {
        let world_entity = world.get_resource::<WorldMarkerEntity>().ok_or(RuntimeError::LiteralError(format!("no WorldMarkerEntity")))?;
        world_entity.0
    };
    let info = {
        let type_regy = world.get_resource::<AppTypeRegistry>().ok_or(RuntimeError::LiteralError(format!("no AppTypeRegistry")))?;
        let assets = world.get_resource::<AssetServer>().ok_or(RuntimeError::LiteralError(format!("no AssetServer")))?;
        let modify = world.get_resource::<ScriptModifyEntities>().ok_or(RuntimeError::LiteralError(format!("no ScriptModifyEntities")))?;
        let ctx: ConvertContext = ConvertContext::new(&rt, &type_regy, &assets, &modify);
        convert_obj_to_value::<SpawnInfo>(&ctx, &args[0])
            .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?
    };

    let mut size = info.size;

    let (mesh, mat, collider) = {
        let models = world.get_resource::<ModelAssets>().ok_or(RuntimeError::LiteralError(format!("no ModelAssets")))?;
        let gmesh = {
            let meshes = world.get_resource::<Assets<GltfMesh>>().ok_or(RuntimeError::LiteralError(format!("no Assets<GltfMesh>")))?;
            meshes.get(&models.tile).ok_or(RuntimeError::LiteralError(format!("no GltfMesh")))?
        };
        let prim = gmesh.primitives[0].clone();

        let mat = gmesh.primitives[0].material.clone();

        let mat = {
            let mut materials = world.get_resource_mut::<Assets<StandardMaterial>>().ok_or(RuntimeError::LiteralError(format!("no Assets<StandardMaterial>")))?;
            match mat.as_ref() {
                Some(mat) => {
                    let mut std_mat = materials.get(mat).unwrap().clone();
                    std_mat.base_color = info.color.mix(&Color::WHITE, 0.75);
                    // std_mat.specular_tint = info.color.mix(&Color::WHITE, 0.25).with_alpha(0.5);
                    // std_mat.specular_tint = info.color.mix(&Color::WHITE, 0.25); //.with_alpha(0.5);
                    materials.add(std_mat)
                },
                None => {
                    materials.add(StandardMaterial {
                        base_color: info.color,
                        perceptual_roughness: 0.75,
                        ..default()
                    })
                }
            }
        };

        let collider = Collider::cuboid(1., 0.025, 1.);

        size.y = size.x.min(size.z);

        (prim.mesh.clone(), mat, collider)
    };

    let new_xfrm = Transform::from_translation(info.offset + xfrm.translation)
        .with_rotation(
            xfrm.rotation *
            Quat::from_euler(
                default(),
                info.angle.x.to_radians(),
                info.angle.y.to_radians(),
                info.angle.z.to_radians())
        )
        .with_scale(size.adjust_precision())
    ;

    let mut queue = CommandQueue::default();
    let mut commands = Commands::new(&mut queue, world);

    let id = commands.spawn((
        (
            ChildOf(world_entity),
            Name::new("SCRIPTED CUBE"),
            Cube,
            Spawned,
            CrosshairTargetable,
            Mesh3d(mesh),
            MeshMaterial3d(mat),
            new_xfrm,
        ),
        (
            if info.is_static { RigidBody::Static } else { RigidBody::Dynamic },
            collider,
            Restitution::new(0.0),
            Friction::new(1.0),
            SleepThreshold {
                linear: 1.0 / 16.0,
                angular: 1.0 / 16.0,
            },
            LinearDamping(1.0 / 16.0),
            AngularDamping(1.0 / 16.0),
            Mass(if info.mass <= 0.0 { 1.0 } else { info.mass }),
            CollisionMargin(0.0025),
        ),
        CollisionLayers::new(
            GameLayer::Projectiles,
            [
                GameLayer::Default,
                GameLayer::World,
                GameLayer::Player,
                GameLayer::Projectiles,
            ],
        ),
        DespawnAfter(match info.life_policy {
            SpawnedLifetimePolicy::Keep => Duration::ZERO,
            SpawnedLifetimePolicy::Temporary { secs } => Duration::from_secs_f32(secs),
        })
    )).id();

    if info.has_synth {
        commands.entity(id).insert(OurMidiSynth);
    }

    queue.apply(world);

    Ok(ExecState::Result(rt.for_typed_uint(&rt.types.u64_type, id.to_bits() as usize)?))
}

/// Set the material to use our palette-mapped extension.
pub(crate) fn set_palette_material(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    mut commands: Commands,
) -> ExecResult {
    if args.len() != 0 {
        return Err(RuntimeError::TooManyArguments(
            Arc::new(BlockId(None, rt.pool.ensure_str_ref("set_palette_material"))),
            args.len() as ArgIndex, 0));
    }

    commands.entity(entity).insert(SpawnPaletteMaterial);

    Ok(ExecState::Result(ObjectPtr::for_nil()))
}
