use std::any::TypeId;
use std::sync::Arc;

use crate::game::Cube;
use crate::game::OurMidiSynth;
use crate::game::UserScript;
use avian3d::math::AdjustPrecision as _;
use bevy::ecs::world::CommandQueue;
use eds_bevy_common::*;

use avian3d::prelude::*;
use bevy::prelude::*;

use fedry_bevy_plugin::bevy_world_function_service::BevyWorldFunctionService;
use fedry_bevy_plugin::prelude::*;
use fedry_runtime::prelude::*;

pub struct ScriptingPlugin;

impl Plugin for ScriptingPlugin {
    fn build(&self, app: &mut App) {
        app
            .add_systems(
                Startup,
                register_funcs,
            )
        ;
    }
}

/// Attributes for a `spawn_cube` call.
#[derive(Reflect, Debug, Clone)]
struct SpawnInfo {
    /// Offset to spawn relative to the caller's position.
    offset: Vec3,
    /// Size of object, in m.
    size: Vec3,
    /// Direction the object should be oriented. Default is Vec3::ZERO.
    angle: Vec3,
    color: Color,
    mass: f32,
    is_static: bool,
    /// The rules for the item.
    life_policy: SpawnedLifetimePolicy,
    has_synth: bool,
}

/// Policy for the object(s) generated by the `spawn_cube` call.
#[derive(Debug, Default, Clone, Copy, PartialEq)]
#[derive(Reflect)]
#[type_path = "game"]
pub enum SpawnedLifetimePolicy {
    /// Create as a temporary object, which will be despawned
    /// after a given amount of game time.
    Temporary{ secs: f32 },
    /// (Try to) keep the object.
    /// This is typically bounded by the current level's end.
    #[default]
    Keep,
}

impl Default for SpawnInfo {
    fn default() -> Self {
        Self {
            offset: Vec3::ZERO,
            size: Vec3::splat(1.0),
            color: Color::WHITE,
            angle: Vec3::ZERO,
            mass: 1.0,
            is_static: false,
            life_policy: SpawnedLifetimePolicy::Keep,
            has_synth: false,
        }
    }
}

fn register_funcs(mut commands: Commands, runtime: Res<ScriptRuntime>) {
    let rt = &runtime.rt;
    let bevy_world_service = rt.get_service::<BevyWorldFunctionService>().expect("expected BevyWorldService");
    bevy_world_service.add_world_func(
        rt.pool.for_str("spawn_cube"),
        commands.register_system(spawn_cube));
    bevy_world_service.add_world_func(
        rt.pool.for_str("send_midi_message"),
        commands.register_system(send_midi_message));
    bevy_world_service.add_world_func(
        rt.pool.for_str("add_script"),
        commands.register_system(add_script));
    bevy_world_service.add_world_func(
        rt.pool.for_str("remove_script"),
        commands.register_system(remove_script));
    bevy_world_service.add_world_func(
        rt.pool.for_str("translate"),
        commands.register_system(translate));
    bevy_world_service.add_world_func(
        rt.pool.for_str("add_velocity"),
        commands.register_system(add_velocity));
}

fn spawn_cube(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>, world: &mut World) -> ExecResult {
    if args.is_empty() {
        return Err(RuntimeError::MissingArgument(0));
    }

    let xfrm = {
        let mut query = world.query::<&Transform>();
        query.get(world, entity).map(|x| *x).unwrap_or_default()
    };
    let world_entity = {
        let world_entity = world.get_resource::<WorldMarkerEntity>().ok_or(RuntimeError::LiteralError(format!("no WorldMarkerEntity")))?;
        world_entity.0
    };
    let info = {
        let type_regy = world.get_resource::<AppTypeRegistry>().ok_or(RuntimeError::LiteralError(format!("no AppTypeRegistry")))?;
        convert_obj_to_value::<SpawnInfo>(&rt, &type_regy, TypeId::of::<SpawnInfo>(), &args[0])
            .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?
    };

    let mesh = {
        let mut meshes = world.get_resource_mut::<Assets<Mesh>>().ok_or(RuntimeError::LiteralError(format!("no Assets<Mesh>")))?;
        meshes.add(Cuboid::from_size(info.size))
    };

    let collider = Collider::cuboid(info.size.x, info.size.y, info.size.z);

    let mat = {
        let mut materials = world.get_resource_mut::<Assets<StandardMaterial>>().ok_or(RuntimeError::LiteralError(format!("no Assets<StandardMaterial>")))?;
        materials.add(StandardMaterial {
            base_color: info.color,
            perceptual_roughness: 0.75,
            ..default()
        })

    };

    let new_xfrm = Transform::from_translation(info.offset + xfrm.translation)
        .with_rotation(
            xfrm.rotation *
            Quat::from_euler(
                default(),
                info.angle.x.to_radians(),
                info.angle.y.to_radians(),
                info.angle.z.to_radians())
        );

    let mut queue = CommandQueue::default();
    let mut commands = Commands::new(&mut queue, world);

    let id = commands.spawn((
        (
            ChildOf(world_entity),
            Name::new("SCRIPTED CUBE"),
            Cube,
            Spawned,
            CrosshairTargetable,
            Mesh3d(mesh),
            MeshMaterial3d(mat),
            new_xfrm,
        ),
        (
            if info.is_static { RigidBody::Static } else { RigidBody::Dynamic },
            collider,
            Restitution::new(0.0),
            Friction::new(1.0),
            SleepThreshold {
                linear: 0.125,
                angular: 0.125,
            },
            LinearDamping(0.125),
            AngularDamping(0.125),
            Mass(if info.mass <= 0.0 { 1.0 } else { info.mass }),
            CollisionMargin(0.001),
        ),
        CollisionLayers::new(
            GameLayer::Projectiles,
            [
                GameLayer::Default,
                GameLayer::World,
                GameLayer::Player,
                GameLayer::Projectiles,
            ],
        ),
        DespawnAfter(match info.life_policy {
            SpawnedLifetimePolicy::Keep => Duration::ZERO,
            SpawnedLifetimePolicy::Temporary { secs } => Duration::from_secs_f32(secs),
        })
    )).id();

    if info.has_synth {
        commands.entity(id).insert(OurMidiSynth);
    }

    queue.apply(world);

    Ok(ExecState::Result(rt.for_typed_uint(&rt.types.u64_type, id.to_bits() as usize)?))
}

fn send_midi_message(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    mut commands: Commands,
    type_regy: Res<AppTypeRegistry>,
) -> ExecResult {
    if args.len() < 1 {
        return Err(RuntimeError::MissingArgument(0));
    }

    let delay = {
        if args.len() >= 2 {
            let Some(delay) = RtNumber::new(&args[1]) else {
                return Err(RuntimeError::LiteralError(format!("expected a number for the delay argument, got {}",
                    RtDisplay::new(&rt, &args[1]))));
            };
            if delay.as_real() < 0.0 {
                return Err(RuntimeError::LiteralError(format!("delay cannot be negative, got {}",
                    RtDisplay::new(&rt, &args[1]))));
            }
            delay.as_real() as f32
        } else {
            0.0f32
        }
    };

    let command = convert_obj_to_value::<SynthCommand>(
        &rt, &type_regy, TypeId::of::<SynthCommand>(), &args[0])
    .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?;

    let message = SynthMessage::new(entity, command).after_secs(delay);
    commands.write_message(message);

    Ok(ExecState::Result(ObjectPtr::for_nil()))
}

fn add_script(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    type_regy: Res<AppTypeRegistry>,
    assets: Res<AssetServer>,
    mut pending: ResMut<PendingScripts>,
) -> ExecResult {
    if args.len() < 1 {
        return Err(RuntimeError::MissingArgument(0));
    }

    let script_info = convert_obj_to_value::<ScriptCreationInfo>(&rt, &type_regy, TypeId::of::<ScriptCreationInfo>(), &args[0])
        .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?;

    let handle = assets.load(&script_info.path);

    pending.insert(PendingScript {
        target: entity,
        handle,
        info: script_info,
    });

    Ok(ExecState::Result(ObjectPtr::for_nil()))
}

fn remove_script(In((entity, _rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    world: &mut World,
) -> ExecResult {
    if args.len() < 1 {
        return Err(RuntimeError::MissingArgument(0));
    }

    world.get_entity_mut(entity)
        .map_err(|e| RuntimeError::LiteralError(format!("failed to remove script: {e}")))?
        .remove::<Script<UserScript>>();

    Ok(ExecState::Result(ObjectPtr::for_nil()))
}

fn translate(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    type_regy: Res<AppTypeRegistry>,
    mut xfrm_q: Query<&mut Transform>,
) -> ExecResult {
    if args.len() < 1 {
        return Err(RuntimeError::MissingArgument(0));
    }

    let offset = convert_obj_to_value::<Vec3>(&rt, &type_regy, TypeId::of::<Vec3>(), &args[0])
        .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?;

    let mut xfrm = xfrm_q.get_mut(entity)
        .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?;

    xfrm.translation += offset;

    Ok(ExecState::Result(ObjectPtr::for_nil()))
}

fn add_velocity(In((entity, rt, args)): In<(Entity, Arc<Runtime>, Vec<ObjectPtr>)>,
    mut commands: Commands,
    type_regy: Res<AppTypeRegistry>,
    mut vel_q: Query<&mut LinearVelocity>,
) -> ExecResult {
    if args.len() < 1 {
        return Err(RuntimeError::MissingArgument(0));
    }

    let new_vel = convert_obj_to_value::<Vec3>(&rt, &type_regy, TypeId::of::<Vec3>(), &args[0])
        .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?;

    let mut vel = vel_q.get_mut(entity)
        .map_err(|e| RuntimeError::LiteralError(format!("{e}")))?;

    vel.0 = vel.0 + new_vel.adjust_precision();

    commands.entity(entity).try_remove::<Sleeping>();
    Ok(ExecState::Result(ObjectPtr::for_nil()))
}
