[build]
rustflags = ["-Z", "threads=4",
 # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[target.x86_64-pc-windows-msvc]
#linker = "c:/Program Files/LLVM/bin/ld.lld"

[package.metadata.bevy_cli.unstable]
web-multi-threading = true

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    # "-C", "link-arg=--shared-memory",
    # "-C", "link-arg=--max-memory=1073741824",
    # "-C", "link-arg=--import-memory",
    # "-C", "link-arg=--export=__wasm_init_tls",
    # "-C", "link-arg=--export=__tls_size",
    # "-C", "link-arg=--export=__tls_align",
    # "-C", "link-arg=--export=__tls_base",
    # Improve performance
    "--cfg", "web_sys_unstable_apis",
    "-Ctarget-feature=+sign-ext,+nontrapping-fptoint",
    # Compile faster
    "-Zshare-generics=y",
    "-Zthreads=8",
]
rustdocflags = [
    # Compile faster
    "-Zshare-generics=y",
    "-Zthreads=4",
]
[unstable]
codegen-backend = true

[profile.'not(any(cfg(target_os = "macos"), cfg(target_arch = "wasm32")))'.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[patch.crates-io]
# Project-level overrides for eds_bevy_common exposed dependencies.
## Support webp
gltf = { git = "https://github.com/gltf-rs/gltf.git", branch = "main" }

# Overrides where the upstream hasn't accepted patches or released new versions.
bevy_skein = { git = "https://github.com/eswartz/skein-fork.git", branch = "add-fallback-for-serde-unit-structs-bevy-0.19" }

# bevy_enhanced_input = { git = "https://github.com/simgine/bevy_enhanced_input.git", rev = "e965c051839b541ad306b17f704f86ff73859ad5" }
# bevy_seedling = { git = "https://github.com/CorvusPrudens/bevy_seedling.git", branch = "master" }
# firewheel = { git = "https://github.com/BillyDM/Firewheel", rev = "68f59e07c5d37ab066342b2bed9afe343b87604f", optional = true }
